repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [ python ]
        require_serial: true
        args: [ "--rcfile=pyproject.toml" ]

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [ python ]
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.17.1
#    hooks:
#      - id: mypy

  - repo: https://github.com/opensource-nepal/commitlint
    rev: v1.3.0
    hooks:
     - id: commitlint